name: J. Metz's homepage
author: J. Metz 
#syntax-highlighting:
#  enabled : true
#  #highlighter: pygments
collections:
  intropython2016:
    title : Introduction to Python 2016
    output : true
  advancedpython2016:
    title : Advanced Python 2016
    output : true
